### ISSUE TITLE
Remove "text me the app" field

### ISSUE THREAD

**Issue by thisisyoon** [comicpanda/tapas.io#9]
Via slack (with Daron)

> Our free credit will expire in February (we still have $745 left over), so we’d have to start paying after February. so… if not many people are using it, we should just turn it off and remove the field on tapas.io tomorrow

![image](https://cloud.githubusercontent.com/assets/1904033/22438156/c0fd8a58-e6df-11e6-8193-b82c927e89dd.png)

**Comment by daronakira** [comment]
I think this means Feb 1...? So ideally we can disable/remove this ASAP (not many people have used it, anyway)
<img width="550" alt="screenshot 2017-01-30 11 34 39" src="https://cloud.githubusercontent.com/assets/952923/22438251/1d2a7ebc-e6e0-11e6-961c-6bc3385472a9.png">

**Comment by daronakira** [comment]
Yoon says "Feb 10, 2017," so I guess we have a little time.

**Comment by thisisyoon** [comment]
Okay :-)
